---
- name: "Playbook for create instance"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: conta-demo@automation-demo-216213.iam.gserviceaccount.com
    credentials_file: /mnt/c/Users/jose.mussauer/Projetos/gcp-ansible-automation/credentials.json
    project_id: automation-demo-216213
    machine_type: g1-small
    image: centos-7-v20180104
    zone: us-central1-a
  
  tasks:
  - name: "Create GCP instance" 
    gce:
      instance_names: "{{ instance_name_1 }},{{ instance_name_2 }}"
      zone: "{{ zone }}"
      machine_type: "{{ machine_type }}"
      state: present
      #tags:
        # - mongodb
        # - criada-via-iac
      image: "{{ image }}"
      disk_auto_delete: true
      ip_forward: true
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
    register: gce

  - name: "Create disk for instance 1" 
    gce_pd:
      instance_name: "{{ instance_name_1 }}"
      delete_on_termination: yes
      size_gb: 50
      name: disk-1
      mode: READ_WRITE
      state: present
      zone: "{{ zone }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Create disk for instance 2" 
    gce_pd:
      instance_name: "{{ instance_name_2 }}"
      delete_on_termination: yes
      size_gb: 50
      name: disk-2
      mode: READ_WRITE
      state: present
      zone: "{{ zone }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: "Waiting SSH"
    wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
    with_items: "{{ gce.instance_data }}"